version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "29200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disabled for easy local development
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - eshop-microservice-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana-dashboard
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_started
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    networks:
      - eshop-microservice-network

volumes:
  es_data:

networks:
  eshop-microservice-network:
    driver: bridge